###
POST {{API_BASE_URL}}/register
Content-Type: application/json

{
  "symbol": "xylli",
  "faction": "COSMIC"
}

###

# curl '{{API_BASE_URL}}/my/agent'
# --header 'Authorization: Bearer INSERT_TOKEN_HERE'
GET {{API_BASE_URL}}/my/agent
Authorization: Bearer {{ACCESS_TOKEN}}

###

# curl '{{API_BASE_URL}}/systems/:systemSymbol/waypoints/:waypointSymbol'
# --header 'Authorization: Bearer INSERT_TOKEN_HERE'
GET {{API_BASE_URL}}/systems/X1-DF55/waypoints/X1-DF55-20250Z
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{API_BASE_URL}}/my/ships/XYLLI-1/cooldown
Accept: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###


