create table api_status
(
    id                     bigint generated by default as identity
        primary key,
    created_at             timestamp,
    last_reset_date        date,
    server_reset_frequency varchar,
    server_reset_next_date timestamp,
    status                 varchar,
    updated_at             timestamp,
    version                varchar
);

