create table agent
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    email      varchar,
    faction    varchar
        constraint agent_faction_check
            check ((faction)::text = ANY
                   ((ARRAY ['COSMIC'::character varying, 'VOID'::character varying, 'GALACTIC'::character varying, 'QUANTUM'::character varying, 'DOMINION'::character varying, 'ASTRO'::character varying, 'CORSAIRS'::character varying, 'OBSIDIAN'::character varying, 'AEGIS'::character varying, 'UNITED'::character varying, 'SOLITARY'::character varying, 'COBALT'::character varying, 'OMEGA'::character varying, 'ECHO'::character varying, 'LORDS'::character varying, 'CULT'::character varying, 'ANCIENTS'::character varying, 'SHADOW'::character varying, 'ETHEREAL'::character varying])::text[])),
    symbol     varchar,
    token      varchar,
    updated_at timestamp
);


