app:
  startup:
    enabled: false
  space-traders-api:
    baseUrl: https://api.spacetraders.io/v2
    accountToken: ""
spring:
  jpa:
    open-in-view: false
  main:
    web-application-type: none
  session:
    jdbc:
      initialize-schema: never