app:
  startup:
    enabled: false
  spaceTradersApi:
    baseUrl: https://api.spacetraders.io/v2
    accessToken: ""
    registeredVersion: "v2"
spring:
  jpa:
    open-in-view: false
  main:
    web-application-type: none
